#
# @(#) $Id: Makefile,v 1.1 2001/04/04 15:34:40 ivm Exp $
#
# $Log: Makefile,v $
# Revision 1.1  2001/04/04 15:34:40  ivm
# Added Makefiles
#
#

DSTMAN = $(DSTROOT)/man

MANFILES = 

upstar: #$(DSTMAN)
#	cp $(MANFILES) $(DSTMAN)
#	cd $(DSTMAN); chmod ugo+r $(MANFILES)

$(DSTMAN):	
	mkdir -p $(DSTMAN)
	

